[versions]
# Required stuff, https://fabricmc.net/develop/
minecraft = "1.21.11"
yarnMappings = "1.21.11+build.4"
fabricLoader = "0.18.4"
fabricApi = "0.141.2+1.21.11"

fabricLanguageKotlin = "1.13.8+kotlin.2.3.0" # https://github.com/FabricMC/fabric-language-kotlin/releases

# Plugins
kotlin = "2.3.0" # Match this to the one above
loom = "1.15-SNAPSHOT" # https://github.com/FabricMC/fabric-loom/releases
modPublish = "1.1.0" # https://github.com/modmuss50/mod-publish-plugin

# Other dependencies
modMenu = "17.0.0-beta.2" # https://github.com/TerraformersMC/ModMenu/releases
yacl = "3.8.2+1.21.11-fabric" # https://modrinth.com/mod/yacl/versions
rimelib = "2.3.5+1.21.11"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarnMappings = { module = "net.fabricmc:yarn", version.ref = "yarnMappings" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricLanguageKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricLanguageKotlin" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
modMenu = { module = "com.terraformersmc:modmenu", version.ref = "modMenu" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
rimelib = { module = "me.ancientri:rimelib", version.ref = "rimelib" }

[bundles]


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
modPublish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modPublish"}